AeagSqeBundle_saisieDonnees_index:
    path:  /lots
    defaults: { _controller: AeagSqeBundle:SaisieDonnees:index }
    
AeagSqeBundle_saisieDonnees_lot_periodes:
    path:  /periodes/{lotanId}
    defaults: { _controller: AeagSqeBundle:SaisieDonnees:lotPeriodes, lotanId : null}    

AeagSqeBundle_saisieDonnees_lot_periode_stations:
    path: /stations/{periodeAnId}
    defaults: { _controller: AeagSqeBundle:SaisieDonnees:lotPeriodeStations, periodeAnId : null}
    
AeagSqeBundle_saisieDonnees_lot_periode_station_saisir_env_situ:
    path:  /saisir/env/{prelevId}/{periodeAnId}/{stationId}/{maj}
    defaults: { _controller: AeagSqeBundle:SaisieDonnees:lotPeriodeStationSaisirEnvSitu, prelevId : null, periodeAnId : null, stationId : null, maj : null}
    requirements:
        methods:  GET|POST
        
AeagSqeBundle_saisieDonnees_lot_periode_station_saisir_ana:
    path:  /saisir/ana/{prelevId}/{periodeAnId}/{stationId}/{maj}
    defaults: { _controller: AeagSqeBundle:SaisieDonnees:lotPeriodeStationSaisirAna, prelevId : null, periodeAnId : null, stationId : null, maj :  null}
    requirements:
        methods:  GET|POST
        
AeagSqeBundle_saisieDonnees_lot_periode_station_env_situ_resultat:
    path:  /resultat/env/{prelevId}/{periodeAnId}/{stationId}
    defaults: { _controller: AeagSqeBundle:SaisieDonnees:lotPeriodeStationResultatEnvSitu, prelevId : null, periodeAnId : null, stationId : null}
    requirements:
        methods:  GET|POST
        
AeagSqeBundle_saisieDonnees_lot_periode_station_ana_resultat:
    path:  /resultat/ana/{prelevId}/{periodeAnId}/{stationId}
    defaults: { _controller: AeagSqeBundle:SaisieDonnees:lotPeriodeStationResultatAna, prelevId : null, periodeAnId : null, stationId : null}
    requirements:
        methods:  GET|POST
        
AeagSqeBundle_saisieDonnees_lot_periode_station_valider:
    path:  /valider/ana/{prelevId}/{periodeAnId}
    defaults: { _controller: AeagSqeBundle:SaisieDonnees:lotPeriodeStationValider, prelevId : null, periodeAnId : null}
    requirements:
        methods:  GET|POST
        
AeagSqeBundle_saisieDonnees_lot_periode_station_devalider:
    path:  /devalider/ana/{prelevId}/{periodeAnId}
    defaults: { _controller: AeagSqeBundle:SaisieDonnees:lotPeriodeStationDevalider, prelevId : null, periodeAnId : null}
    requirements:
        methods:  GET|POST
        
AeagSqeBundle_saisieDonnees_lot_periode_station_telecharger:
    path:  /fichier/telecharger/{prelevId}
    defaults: { _controller: AeagSqeBundle:SaisieDonnees:lotPeriodeStationTelecharger, prelevId : null}
    requirements:
         methods:  GET|POST
        
        
    
AeagSqeBundle_saisieDonnees_lot_periode_lacs:
    path: /lacs/{periodeAnId}
    defaults: { _controller: AeagSqeBundle:SaisieDonnees:lotPeriodeLacs, periodeAnId : null}
    
AeagSqeBundle_saisieDonnees_lot_periode_lac_saisir_env_situ:
    path:  /saisir_lac/env/{demandeId}/{periodeAnId}/{stationId}/{maj}
    defaults: { _controller: AeagSqeBundle:SaisieDonnees:lotPeriodeLacSaisirEnvSitu,demandeId : null, periodeAnId : null, stationId : null, maj : null}
    requirements:
        methods:  GET|POST
        
AeagSqeBundle_saisieDonnees_lot_periode_lac_saisir_ana:
    path:  /saisir_lac/ana/{prelevId}/{periodeAnId}/{stationId}/{maj}
    defaults: { _controller: AeagSqeBundle:SaisieDonnees:lotPeriodeLacSaisirAna, prelevId : null, periodeAnId : null, stationId : null, maj :  null}
    requirements:
        methods:  GET|POST
        
AeagSqeBundle_saisieDonnees_lot_periode_lac_env_situ_resultat:
    path:  /resultat_lac/env/{demandeId}/{periodeAnId}/{stationId}
    defaults: { _controller: AeagSqeBundle:SaisieDonnees:lotPeriodeLacResultatEnvSitu, demandeId : null, periodeAnId : null, stationId : null}
    requirements:
        methods:  GET|POST
        
AeagSqeBundle_saisieDonnees_lot_periode_lac_env_situ_generer:
    path:  /generer/env/{periodeAnId}/{prelevId}/{groupeId}/{profMax}/{ecart}
    defaults: { _controller: AeagSqeBundle:SaisieDonnees:lotPeriodeLacGenererEnvSitu, periodeAnId : null, prelevId : null, groupeId : null,  profMax : null, ecart : null}
    requirements:
        methods:  GET|POST
        
AeagSqeBundle_saisieDonnees_lot_periode_lac_ana_resultat:
    path:  /resultat_lac/ana/{prelevId}/{periodeAnId}/{stationId}
    defaults: { _controller: AeagSqeBundle:SaisieDonnees:lotPeriodeLacResultatAna, prelevId : null, periodeAnId : null, stationId : null}
    requirements:
        methods:  GET|POST
        
AeagSqeBundle_saisieDonnees_lot_periode_lac_valider:
    path:  /valider_lac/ana/{demandeId}/{periodeAnId}/{stationId}
    defaults: { _controller: AeagSqeBundle:SaisieDonnees:lotPeriodeLacValider, demandeId : null, periodeAnId : null, stationId : null}
    requirements:
        methods:  GET|POST
        
AeagSqeBundle_saisieDonnees_lot_periode_lac_devalider:
    path:  /devalider_lac/ana//{demandeId}/{periodeAnId}/{stationId}
    defaults: { _controller: AeagSqeBundle:SaisieDonnees:lotPeriodeLacDevalider, demandeId : null, periodeAnId : null, stationId : null}
    requirements:
        methods:  GET|POST
        
AeagSqeBundle_saisieDonnees_lot_periode_lac_telecharger:
    path:  /fichier_lac/telecharger/{prelevId}
    defaults: { _controller: AeagSqeBundle:SaisieDonnees:lotPeriodeLacTelecharger, prelevId : null}
    requirements:
         methods:  GET|POST
        

        

