AeagSqeBundle_suiviPrelevements_index:
    path:  /lots
    defaults: { _controller: AeagSqeBundle:SuiviPrelevements:index }
    
AeagSqeBundle_suiviPrelevements_lot_periodes:
    path:  /periodes/{lotanId}
    defaults: { _controller: AeagSqeBundle:SuiviPrelevements:lotPeriodes, lotanId : null}    

AeagSqeBundle_suiviPrelevements_lot_periode_stations:
    path: /stations/{periodeAnId}
    defaults: { _controller: AeagSqeBundle:SuiviPrelevements:lotPeriodeStations, periodeAnId : null}
    
AeagSqeBundle_suiviPrelevements_lot_periode_station_demande:
    path:  /demande/{stationId}/{periodeAnId}/{cmdDemandeId}
    defaults: { _controller: AeagSqeBundle:SuiviPrelevements:lotPeriodeStationDemande, stationId : null, periodeAnId : null, cmdDemandeId : null}

AeagSqeBundle_suiviPrelevements_lot_periode_station_demande_suivi_new:
    path:  /new/{prelevId}/{periodeAnId}
    defaults: { _controller: AeagSqeBundle:SuiviPrelevements:lotPeriodeStationDemandeSuiviNew, prelevId : null, periodeAnId : null}
    requirements:
        methods:  GET|POST
        
AeagSqeBundle_suiviPrelevements_lot_periode_station_demande_suivi_maj:
    path:  /maj/{suiviPrelId}/{periodeAnId}
    defaults: { _controller: AeagSqeBundle:SuiviPrelevements:lotPeriodeStationDemandeSuiviMaj, suiviPrelId : null, periodeAnId : null}
    requirements:
         methods:  GET|POST
         
AeagSqeBundle_suiviPrelevements_lot_periode_station_demande_suivi_voir:
    path:  /voir/{suiviPrelId}/{periodeAnId}
    defaults: { _controller: AeagSqeBundle:SuiviPrelevements:lotPeriodeStationDemandeSuiviVoir, suiviPrelId : null, periodeAnId : null}
    requirements:
         methods:  GET|POST
         
AeagSqeBundle_suiviPrelevements_lot_periode_station_demande_suivi_deposer:
    path:  /deposer/{suiviPrelId}/{periodeAnId}
    defaults: { _controller: AeagSqeBundle:SuiviPrelevements:lotPeriodeStationDemandeSuiviDeposer, suiviPrelId : null, periodeAnId : null}
    requirements:
         methods:  GET|POST
   
AeagSqeBundle_suiviPrelevements_lot_periode_station_demande_suivi_supprimer:
    path:  /supprimer/{suiviPrelId}/{periodeAnId}
    defaults: { _controller: AeagSqeBundle:SuiviPrelevements:lotPeriodeStationDemandeSuiviSupprimer, suiviPrelId : null, periodeAnId : null}
    requirements:
        methods:  GET|POST
  
AeagSqeBundle_suiviPrelevements_lot_periode_station_demande_suivi_fichier_deposer:
    path:  /fichier/deposer/{suiviPrelId}/{periodeAnId}
    defaults: { _controller: AeagSqeBundle:SuiviPrelevements:lotPeriodeStationDemandeSuiviFichierDeposer, suiviPrelId : null, periodeAnId : null }
    requirements:
        methods:  GET|POST
        
AeagSqeBundle_suiviPrelevements_lot_periode_station_demande_suivi_fichier_supprimer:
    path:  /fichier/supprimer/{suiviPrelId}/{periodeAnId}
    defaults: { _controller: AeagSqeBundle:SuiviPrelevements:lotPeriodeStationDemandeSuiviFichierSupprimer, suiviPrelId : null, periodeAnId : null }
    requirements:
        methods:  GET|POST
        
AeagSqeBundle_suiviPrelevements_lot_periode_station_demande_suivi_fichier_telecharger:
    path:  /fichier/telecharger/{suiviPrelId}
    defaults: { _controller: AeagSqeBundle:SuiviPrelevements:lotPeriodeStationDemandeSuiviFichierTelecharger, suiviPrelId : null}
    requirements:
         methods:  GET|POST
