AeagSqeBundle_suiviHydrobio_index:
    path:  /lots
    defaults: { _controller: AeagSqeBundle:SuiviHydrobio:index }
    
AeagSqeBundle_suiviHydrobio_lot_periodes:
    path:  /periodes/{lotanId}
    defaults: { _controller: AeagSqeBundle:SuiviHydrobio:lotPeriodes, lotanId : null}    

AeagSqeBundle_suiviHydrobio_lot_periode_stations:
    path: /stations/{periodeAnId}
    defaults: { _controller: AeagSqeBundle:SuiviHydrobio:lotPeriodeStations, periodeAnId : null}
    
AeagSqeBundle_suiviHydrobio_lot_periode_stations_integrer:
    path: /integrer/{periodeAnId}
    defaults: { _controller: AeagSqeBundle:SuiviHydrobio:lotPeriodeStationsIntegrer, periodeAnId : null}
    
AeagSqeBundle_suiviHydrobio_lot_periode_stations_integrer_fichier:
    path:  /integrer/fichier/{periodeAnId}
    defaults: { _controller: AeagSqeBundle:SuiviHydrobio:lotPeriodeStationsIntegrerFichier, periodeAnId : null }
    requirements:
        methods:  GET|POST
        
AeagSqeBundle_suiviHydrobio_lot_periode_stations_supprimer_fichier:
    path:  /integrer/supprimer/fichier/{periodeAnId}/{fichier}
    defaults: { _controller: AeagSqeBundle:SuiviHydrobio:lotPeriodeStationsSupprimerFichier, periodeAnId : null, fichier : null }
    requirements:
        methods:  GET|POST
        
AeagSqeBundle_suiviHydrobio_lot_periode_stations_telecharger_rapport:
    path:  /rapport/telecharger/{periodeAnId}/{fichier}
    defaults: { _controller: AeagSqeBundle:SuiviHydrobio:lotPeriodeStationsTelechargerRapport, periodeAnId : null, fichier : null}
    requirements:
         methods:  GET|POST
         
AeagSqeBundle_suiviHydrobio_lot_periode_stations_importer:
    path: /importer/{periodeAnId}
    defaults: { _controller: AeagSqeBundle:SuiviHydrobio:lotPeriodeStationsImporter, periodeAnId : null}
    
AeagSqeBundle_suiviHydrobio_lot_periode_stations_importer_fichier:
    path:  /importer/fichier/{periodeAnId}
    defaults: { _controller: AeagSqeBundle:SuiviHydrobio:lotPeriodeStationsImporterFichier, periodeAnId : null }
    requirements:
        methods:  GET|POST
        
AeagSqeBundle_suiviHydrobio_lot_periode_stations_supprimer_import:
    path:  /importer/supprimet/fichier/{periodeAnId}/{fichier}
    defaults: { _controller: AeagSqeBundle:SuiviHydrobio:lotPeriodeStationsSupprimerImport, periodeAnId : null, fichier : null }
    requirements:
        methods:  GET|POST   
    
AeagSqeBundle_suiviHydrobio_lot_periode_station_demande:
    path:  /demande/{stationId}/{periodeAnId}/{cmdDemandeId}
    defaults: { _controller: AeagSqeBundle:SuiviHydrobio:lotPeriodeStationDemande, stationId : null, periodeAnId : null, cmdDemandeId : null}

AeagSqeBundle_suiviHydrobio_lot_periode_station_demande_suivi_new:
    path:  /new/{prelevId}/{periodeAnId}
    defaults: { _controller: AeagSqeBundle:SuiviHydrobio:lotPeriodeStationDemandeSuiviNew, prelevId : null, periodeAnId : null}
    requirements:
        methods:  GET|POST
        
AeagSqeBundle_suiviHydrobio_lot_periode_station_demande_suivi_maj:
    path:  /maj/{suiviPrelId}/{periodeAnId}
    defaults: { _controller: AeagSqeBundle:SuiviHydrobio:lotPeriodeStationDemandeSuiviMaj, suiviPrelId : null, periodeAnId : null}
    requirements:
         methods:  GET|POST
         
AeagSqeBundle_suiviHydrobio_lot_periode_station_demande_suivi_voir:
    path:  /voir/{suiviPrelId}/{periodeAnId}
    defaults: { _controller: AeagSqeBundle:SuiviHydrobio:lotPeriodeStationDemandeSuiviVoir, suiviPrelId : null, periodeAnId : null}
    requirements:
         methods:  GET|POST
         
AeagSqeBundle_suiviHydrobio_lot_periode_station_demande_suivi_deposer:
    path:  /deposer/{suiviPrelId}/{periodeAnId}
    defaults: { _controller: AeagSqeBundle:SuiviHydrobio:lotPeriodeStationDemandeSuiviDeposer, suiviPrelId : null, periodeAnId : null}
    requirements:
         methods:  GET|POST
   
AeagSqeBundle_suiviHydrobio_lot_periode_station_demande_suivi_supprimer:
    path:  /supprimer/{suiviPrelId}/{periodeAnId}
    defaults: { _controller: AeagSqeBundle:SuiviHydrobio:lotPeriodeStationDemandeSuiviSupprimer, suiviPrelId : null, periodeAnId : null}
    requirements:
        methods:  GET|POST
  
AeagSqeBundle_suiviHydrobio_lot_periode_station_demande_suivi_fichier_deposer:
    path:  /fichier/deposer/{suiviPrelId}/{periodeAnId}
    defaults: { _controller: AeagSqeBundle:SuiviHydrobio:lotPeriodeStationDemandeSuiviFichierDeposer, suiviPrelId : null, periodeAnId : null }
    requirements:
        methods:  GET|POST
        
AeagSqeBundle_suiviHydrobio_lot_periode_station_demande_suivi_fichier_supprimer:
    path:  /fichier/supprimer/{suiviPrelId}/{periodeAnId}
    defaults: { _controller: AeagSqeBundle:SuiviHydrobio:lotPeriodeStationDemandeSuiviFichierSupprimer, suiviPrelId : null, periodeAnId : null }
    requirements:
        methods:  GET|POST
        
AeagSqeBundle_suiviHydrobio_lot_periode_station_demande_suivi_fichier_telecharger:
    path:  /fichier/telecharger/{suiviPrelId}
    defaults: { _controller: AeagSqeBundle:SuiviHydrobio:lotPeriodeStationDemandeSuiviFichierTelecharger, suiviPrelId : null}
    requirements:
         methods:  GET|POST
         
AeagSqeBundle_suiviHydrobio_synthese:
    path:  /synthese    
    defaults: { _controller: AeagSqeBundle:SuiviHydrobio:synthese}
    requirements:
         methods:  GET|POST
         
AeagSqeBundle_suiviHydrobio_synthese_support:
    path:  /synthese/support/{codeSupport}   
    defaults: { _controller: AeagSqeBundle:SuiviHydrobio:syntheseSupport, codeSupport: null}
    requirements:
         methods:  GET|POST
         
AeagSqeBundle_suiviHydrobio_synthese_support_station:
    path:  /synthese/support/station/{codeSupport}/{stationId}/{suiviPrelId}/{tr}
    defaults: { _controller: AeagSqeBundle:SuiviHydrobio:syntheseSupportStation, codeSupport: null, stationId : null, suiviPrelId : null, tr: null }
    requirements:
         methods:  GET|POST
         
AeagSqeBundle_suiviHydrobio_synthese_support_station_valider:
    path:  /synthese/support/station/valider/{codeSupport}/{stationId}/{suiviPrelId}/{tr}
    defaults: { _controller: AeagSqeBundle:SuiviHydrobio:syntheseSupportStationvalider, codeSupport: null, stationId : null, suiviPrelId : null, tr: null }
    requirements:
         methods:  GET|POST
         
AeagSqeBundle_suiviHydrobio_planning:
    path:  /planning
    defaults: { _controller: AeagSqeBundle:SuiviHydrobio:planning }
    
AeagSqeBundle_suiviHydrobio_planning_table:
    path:  /planning/table
    defaults: { _controller: AeagSqeBundle:SuiviHydrobio:planningTable }
