aeag_sqe:
    path:  /
    defaults: { _controller: AeagSqeBundle:Default:index }
    
aeag_sqe_admin:
    resource: "@AeagSqeBundle/Resources/config/routing_admin.yml"
    prefix:   /adminsqe

aeag_sqe_referentiel:
    resource: "@AeagSqeBundle/Resources/config/routing_referentiel.yml"
    prefix:   /referentiel
    
aeag_sqe_programmation:
    resource: "@AeagSqeBundle/Resources/config/routing_programmation.yml"
    prefix:   /programmation
    
aeag_sqe_envoyerMessage:
    path:  /message/envoyer
    defaults: { _controller: AeagSqeBundle:Default:envoyerMessage }
    requirements:
        methods:  GET|POST
        
aeag_sqe_echangeFichiers:
    resource: "@AeagSqeBundle/Resources/config/routing_echangefichiers.yml"
    prefix:   /echangefichiers   
    
aeag_sqe_suiviHydrobio:
    resource: "@AeagSqeBundle/Resources/config/routing_suiviHydrobio.yml"
    prefix:   /suiviHydrobio 
    
aeag_sqe_SaisieDonnees:
    resource: "@AeagSqeBundle/Resources/config/routing_saisieDonnees.yml"
    prefix:   /saisieDonnees
    
aeag_sqe_suiviSediment:
    resource: "@AeagSqeBundle/Resources/config/routing_suiviSediment.yml"
    prefix:   /suiviSediment 
    
aeag_sqe_planning:
    resource: "@AeagSqeBundle/Resources/config/routing_planning.yml"
    prefix:   /planning  
    
aeag_sqe_exportDonneesBrutes:
    resource: "@AeagSqeBundle/Resources/config/routing_exportdonneesbrutes.yml"
    prefix:   /exportdonneesbrutes    
 