parameters:
    aeag_sqe.tools.class: Aeag\SqeBundle\Utils\Tools
    
services:
    # keep your service names short
    aeag_sqe.tools:
        class: %aeag_sqe.tools.class%
#       arguments: [@service_id, "plain_value", %parameter%]
