parameters:
    aeag_sqe.tools.class: Aeag\SqeBundle\Utils\Tools
    aeag_sqe.process_rai.class: Aeag\SqeBundle\Utils\ProcessRai
    aeag_sqe.message.class: Aeag\SqeBundle\Utils\MessageMaker
    aeag_sqe.controle_vraisemblance.class: Aeag\SqeBundle\Utils\ControleVraisemblance
    
services:
    # keep your service names short
    aeag_sqe.tools:
        class: %aeag_sqe.tools.class%
#       arguments: [@service_id, "plain_value", %parameter%]
    aeag_sqe.process_rai:
        class: %aeag_sqe.process_rai.class%
    aeag_sqe.message:
        class: %aeag_sqe.message.class%
        arguments: [@mailer]
    aeag_sqe.controle_vraisemblance:
        class: %aeag_sqe.controle_vraisemblance.class%
