parameters:
#    aeag_sqe.example.class: Aeag\SqeBundle\Example

services:
#    aeag_sqe.example:
#        class: %aeag_sqe.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
