#!/bin/bash
cp -R /base/extranet/preprod/ext_aeag /base/extranet/preprod/ext_aeag_release

find /base/extranet/preprod/ext_aeag_release | grep .git | xargs rm -rf
rm -Rf /base/extranet/preprod/ext_aeag_release/app/logs/*
rm -Rf /base/extranet/preprod/ext_aeag_release/app/cache/*
rm -Rf /base/extranet/preprod/ext_aeag_release/mise-en-prod.sh


scp -rp /base/extranet/preprod/ext_aeag_release root@vslin30112:/base/extranet/ext_aeag_release
ssh root@vslin30112 '/usr/local/bin/update_site_sqe.sh'
rm -Rf /base/extranet/preprod/ext_aeag_release

