organisme:
    path:  /
    defaults: { _controller: "AeagDieBundle:Organisme:index" }

organisme_show:
    path:  /{id}/show
    defaults: { _controller: "AeagDieBundle:Organisme:show" }

organisme_new:
    path:  /new
    defaults: { _controller: "AeagDieBundle:Organisme:new" }

organisme_create:
    path:  /create
    defaults: { _controller: "AeagDieBundle:Organisme:create" }
    requirements: { methods: post }

organisme_edit:
    path:  /{id}/edit
    defaults: { _controller: "AeagDieBundle:Organisme:edit" }

organisme_update:
    path:  /{id}/update
    defaults: { _controller: "AeagDieBundle:Organisme:update" }
    requirements: { methods: post }

organisme_delete:
    path:  /{id}/delete
    defaults: { _controller: "AeagDieBundle:Organisme:delete" }

