aeag_agent:
    path:  /
    defaults: { _controller: AeagAgentBundle:Default:RechercheEtat }
    requirements:
        methods:  GET|POST
    
aeag_agent_liste:
    path:  /liste
    defaults: { _controller: AeagAgentBundle:Default:listeAgents }
    requirements:
        methods:  GET|POST
        
aeag_agent_recherche_etat:
    path:  /recherche
    defaults: { _controller: AeagAgentBundle:Default:RechercheEtat }
    requirements:
        methods:  GET|POST
        
aeag_agent_resultat_etat:
    path:  /resultat
    defaults: { _controller: AeagAgentBundle:Default:ResultatEtat }
    requirements:
        methods:  GET|POST
        
aeag_service_resultat_etat:
    path:  /resultat/service/{service}
    defaults: { _controller: AeagAgentBundle:Default:ResultatServiceEtat, service : null }
    requirements:
        methods:  GET|POST
