parameters:
#    aeag_agent.example.class: Aeag\AgentBundle\Example

services:
#    aeag_agent.example:
#        class: %aeag_agent.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
