parameters:
#    aeag_dec.example.class: Aeag\DecBundle\Example

services:
#    aeag_dec.example:
#        class: %aeag_dec.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]


