imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

#monolog:
#    handlers:
#        main:
#            type:   stream
#            path:   "%kernel.logs_dir%/%kernel.environment%.log"
#            level:  debug
#        console:
#            type:   console
#            bubble: false
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type:   firephp
        #    level:  info
        #chromephp:
        #    type:   chromephp
        #    level:  info

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type:  console

assetic:
    use_controller: true

swiftmailer:
    #delivery_address: jle@eau-adour-garonne.fr
    delivery_address: frederic.sibien@eau-adour-garonne.fr
    

