aeag_aeag:
    resource: "@AeagAeagBundle/Resources/config/routing.yml"
    prefix:   /
    
aeag_dec:
    resource: "@AeagDecBundle/Resources/config/routing.yml"
    prefix:   /dec
    
aeag_frd:
    resource: "@AeagFrdBundle/Resources/config/routing.yml"
    prefix:   /frd
    
aeag_aide:
    resource: "@AeagAideBundle/Resources/config/routing.yml"
    prefix:   /aide
    
aeag_sqe:
    resource: "@AeagSqeBundle/Resources/config/routing.yml"
    prefix:   /sqe
    
AeagDieBundle:
    resource: "@AeagDieBundle/Resources/config/routing.yml"
    prefix:   /die
    
aeag_user:
    resource: "@AeagUserBundle/Resources/config/routing.yml"
    prefix:   /user
    
  
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile
    

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /change-password 
    