livreor:
    path:     /
    defaults: { _controller: "AeagAeagBundle:LivreOr:index" }

livreor_new:
    path:     /new
    defaults: { _controller: "AeagAeagBundle:LivreOr:new" }

livreor_create:
    path:     /create
    defaults: { _controller: "AeagAeagBundle:LivreOr:create" }
    methods:  POST

livreor_delete:
    path:     /{id}/delete
    defaults: { _controller: "AeagAeagBundle:LivreOr:delete" }
    methods:  [POST,GET]
