#!/usr/bin/env php
<?php
// app/console_process_rai

use Aeag\SqeBundle\Command\GreetCommand;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new GreetCommand);
$application->run();