
AeagEdlBundle_homepage:
    pattern:  /
    defaults: { _controller: AeagEdlBundle:Default:index }
    prefix: /
    requirements:
        _method:  GET|POST
        
AeagEdlBundle_contact:
    pattern:  /contact
    defaults: { _controller: AeagEdlBundle:Default:contact }
    requirements:
        _method:  GET|POST

AeagEdlBundle_massedeau:
    pattern:  /avis/massedeau/{code}
    defaults: { _controller: AeagEdlBundle:Default:massedeau }
    

AeagEdlBundle_pressionForm:
    pattern:  /avis/pressionForm
    defaults: { _controller: AeagEdlBundle:Pression:pressionForm }
    
AeagEdlBundle_pressionSubmit:
    pattern:  /avis/pressionSubmit
    defaults: { _controller: AeagEdlBundle:Pression:pressionSubmit }    
    
AeagEdlBundle_pressionListProposed:
    pattern:  /avis/pressionListProposed
    defaults: { _controller: AeagEdlBundle:Pression:pressionListProposed }        
    
AeagEdlBundle_removePression:
    pattern:  /avis/removePression
    defaults: { _controller: AeagEdlBundle:Pression:removePression }
    
AeagEdlBundle_pression:
    pattern:  /avis/pression/{code}
    defaults: { _controller: AeagEdlBundle:Default:pression }
    
AeagEdlBundle_pressionGroupe:
    pattern:  /avis/pressiongroupe/{code}
    defaults: { _controller: AeagEdlBundle:Default:pressionGroupe }
    
    
AeagEdlBundle_etatForm:
    pattern:  /avis/etatForm
    defaults: { _controller: AeagEdlBundle:Etat:etatForm }
    

AeagEdlBundle_etatSubmit:
    pattern:  /avis/etatSubmit
    defaults: { _controller: AeagEdlBundle:Etat:etatSubmit }    
    
AeagEdlBundle_etatListProposed:
    pattern:  /avis/etatListProposed
    defaults: { _controller: AeagEdlBundle:Etat:etatListProposed }        
    
AeagEdlBundle_removeEtat:
    pattern:  /avis/removeEtat
    defaults: { _controller: AeagEdlBundle:Etat:removeEtat }
    
AeagEdlBundle_etat:
    pattern:  /avis/etat/{code}
    defaults: { _controller: AeagEdlBundle:Default:etat }
    
AeagEdlBundle_etatGroupe1:
    pattern:  /avis/etatgroupe/{code}/{page}
    defaults: { _controller: AeagEdlBundle:Default:etatGroupe }

AeagEdlBundle_etatGroupe:
    pattern:  /avis/etatgroupe/{code}
    defaults: { _controller: AeagEdlBundle:Default:etatGroupe }
    
    
AeagEdlBundle_impactForm:
    pattern:  /avis/impactForm
    defaults: { _controller: AeagEdlBundle:Impact:impactForm }
    
AeagEdlBundle_impactSubmit:
    pattern:  /avis/impactSubmit
    defaults: { _controller: AeagEdlBundle:Impact:impactSubmit }    
    
AeagEdlBundle_impactListProposed:
    pattern:  /avis/impactListProposed
    defaults: { _controller: AeagEdlBundle:Impact:impactListProposed }        
    
AeagEdlBundle_removeImpact:
    pattern:  /avis/removeImpact
    defaults: { _controller: AeagEdlBundle:Impact:removeImpact }
    
AeagEdlBundle_impact:
    pattern:  /avis/impact/{code}
    defaults: { _controller: AeagEdlBundle:Default:impact }
    
AeagEdlBundle_impactGroupe:
    pattern:  /avis/impactgroupe/{code}
    defaults: { _controller: AeagEdlBundle:Default:impactGroupe }
    
    
    
AeagEdlBundle_risqueForm:
    pattern:  /avis/risqueForm
    defaults: { _controller: AeagEdlBundle:Risque:risqueForm }
    
AeagEdlBundle_risqueSubmit:
    pattern:  /avis/risqueSubmit
    defaults: { _controller: AeagEdlBundle:Risque:risqueSubmit }    
    
AeagEdlBundle_risqueListProposed:
    pattern:  /avis/risqueListProposed
    defaults: { _controller: AeagEdlBundle:Risque:risqueListProposed }        
    
AeagEdlBundle_removeRisque:
    pattern:  /avis/removeRisque
    defaults: { _controller: AeagEdlBundle:Risque:removeRisque }
    
AeagEdlBundle_risque:
    pattern:  /avis/risque/{code}
    defaults: { _controller: AeagEdlBundle:Default:risque }
    
AeagEdlBundle_risqueGroupe:
    pattern:  /avis/risquegroupe/{code}
    defaults: { _controller: AeagEdlBundle:Default:risqueGroupe }
     

AeagEdlBundle_rechercherMasseEau:
    pattern: /avis/masseEau/rechercher
    defaults: { _controller: AeagEdlBundle:Default:rechercherMasseEau }
    requirements:
         _method: POST
   
    
AeagEdlBundle_listeMasseEau:
    pattern: /avis/ListeEtat
    defaults: { _controller: "AeagEdlBundle:Default:listeMasseEau" }


fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /change-password  
    
AeagUtilisateurBundle_utilisateur:
    pattern:  /utilisateur
    defaults: { _controller: AeagUtilisateurBundle:Utilisateur:index }
    prefix: /utilisateur
    requirements:
        _method:  GET
        

AeagUtilisateurBundle_utilisateur_show:
    pattern:  /utilisateur/{id}/show
    defaults: { _controller: "AeagUtilisateurBundle:Utilisateur:show" }

AeagUtilisateurBundle_utilisateur_new:
    pattern:  /utilisateur/new
    defaults: { _controller: "AeagUtilisateurBundle:Utilisateur:new" }

AeagUtilisateurBundle_utilisateur_create:
    pattern:  /utilisateur/create
    defaults: { _controller: "AeagUtilisateurBundle:Utilisateur:create" }
    requirements: { _method: post }

AeagUtilisateurBundle_utilisateur_edit:
    pattern:  /utilisateur/{id}/edit
    defaults: { _controller: "AeagUtilisateurBundle:Utilisateur:edit" }

AeagUtilisateurBundle_utilisateur_update:
    pattern:  /utilisateur/{id}/update
    defaults: { _controller: "AeagUtilisateurBundle:Utilisateur:update" }
    requirements:
        _method:  GET|POST

AeagUtilisateurBundle_utilisateur_delete:
    pattern:  /utilisateur/{id}/delete
    defaults: { _controller: "AeagUtilisateurBundle:Utilisateur:delete" }
    requirements:
        _method:  GET|POST


   