
aeag_edl:
    path:  /
    defaults: { _controller: AeagEdlBundle:Default:index }
    prefix: /
    requirements:
        methods:  GET|POST
        
AeagEdlBundle_rechercherMasseEau:
    path: /avis/masseEau/rechercher
    defaults: { _controller: AeagEdlBundle:Default:rechercherMasseEau }
    requirements:
         methods: POST
      
AeagEdlBundle_listeMasseEau:
    path: /avis/ListeEtat
    defaults: { _controller: "AeagEdlBundle:Default:listeMasseEau" }
    
    

AeagEdlBundle_etatGroupe:
    path:  /avis/etatgroupe/{code}
    defaults: { _controller: AeagEdlBundle:Default:etatGroupe }
    
AeagEdlBundle_etat:
    path:  /avis/etat/{code}
    defaults: { _controller: AeagEdlBundle:Default:etat }
    
AeagEdlBundle_etatListProposed:
    path:  /avis/etatListProposed
    defaults: { _controller: AeagEdlBundle:Etat:etatListProposed }        
    
AeagEdlBundle_removeEtat:
    path:  /avis/removeEtat
    defaults: { _controller: AeagEdlBundle:Etat:removeEtat }
    
AeagEdlBundle_etatForm:
    path:  /avis/etatForm
    defaults: { _controller: AeagEdlBundle:Etat:etatForm }

AeagEdlBundle_etatSubmit:
    path:  /avis/etatSubmit
    defaults: { _controller: AeagEdlBundle:Etat:etatSubmit }    
    
AeagEdlBundle_ExportEtat:
    path:  /avis/etatExport
    defaults: { _controller: AeagEdlBundle:Default:exportEtat }    
    
    
    
AeagEdlBundle_pressionGroupe:
    path:  /avis/pressiongroupe/{code}
    defaults: { _controller: AeagEdlBundle:Default:pressionGroupe }
    
AeagEdlBundle_pression:
    path:  /avis/pression/{code}
    defaults: { _controller: AeagEdlBundle:Default:pression }
    
AeagEdlBundle_pressionForm:
    path:  /avis/pressionForm
    defaults: { _controller: AeagEdlBundle:Pression:pressionForm }
    
AeagEdlBundle_pressionSubmit:
    path:  /avis/pressionSubmit
    defaults: { _controller: AeagEdlBundle:Pression:pressionSubmit }    
    
AeagEdlBundle_pressionListProposed:
    path:  /avis/pressionListProposed
    defaults: { _controller: AeagEdlBundle:Pression:pressionListProposed }        
    
AeagEdlBundle_removePression:
    path:  /avis/removePression
    defaults: { _controller: AeagEdlBundle:Pression:removePression }
    
AeagEdlBundle_ExportPression:
    path:  /avis/pressionExport
    defaults: { _controller: AeagEdlBundle:Default:exportPression }    
     
        
AeagEdlBundle_contact:
    path:  /contact
    defaults: { _controller: AeagEdlBundle:Default:contact }
    requirements:
        methods:  GET|POST

AeagEdlBundle_massedeau:
    path:  /avis/massedeau/{code}
    defaults: { _controller: AeagEdlBundle:Default:massedeau }
    

AeagEdlBundle_utilisateur:
    path:  /utilisateur
    defaults: { _controller: AeagEdlBundle:Utilisateur:index }
    prefix: /utilisateur
    requirements:
        methods:  GET
        

AeagEdlBundle_utilisateur_show:
    path:  /utilisateur/{id}/show
    defaults: { _controller: "AeagEdlBundle:Utilisateur:show" }

AeagEdlBundle_utilisateur_new:
    path:  /utilisateur/new
    defaults: { _controller: "AeagEdlBundle:Utilisateur:new" }

AeagEdlBundle_utilisateur_create:
    path:  /utilisateur/create
    defaults: { _controller: "AeagEdlBundle:Utilisateur:create" }
    requirements: { methods: post }

AeagEdlBundle_utilisateur_edit:
    path:  /utilisateur/{id}/edit
    defaults: { _controller: "AeagEdlBundle:Utilisateur:edit" }

AeagEdlBundle_utilisateur_update:
    path:  /utilisateur/{id}/update
    defaults: { _controller: "AeagEdlBundle:Utilisateur:update" }
    requirements:
        methods:  GET|POST

AeagEdlBundle_utilisateur_delete:
    path:  /utilisateur/{id}/delete
    defaults: { _controller: "AeagEdlBundle:Utilisateur:delete" }
    requirements:
        methods:  GET|POST


   