parameters:
#    aeag_user.example.class: Aeag\UserBundle\Example

services:
#    aeag_user.example:
#        class: %aeag_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
