#!/bin/bash
jour=$(date +"%Y%m%d")
dir="/base/extranet/preprod/ext_aeag/app/logs/rai"
if [ -d "$dir" ]; then
  php /base/extranet/preprod/ext_aeag/app/console_process_rai rai:backup_process >> $dir/process_$jour.log
else
  mkdir $dir
fi
