#!/bin/bash
jour=$(date +"%Y%m%d")
dir="/base/extranet/preprod/ext_aeag/app/logs"
if [ ! -d "$dir" ]; then
  mkdir $dir
fi
php /base/extranet/preprod/ext_aeag/app/console_process_rai rai:backup_process >> $dir/process_$jour.log
