#!/bin/bash
jour=$(date +"%Y%m%d")
if [ "$1" = "-env" ]; then
    if [ "$2" = "prod" ]; then
        dirbase="/base/extranet/ext_aeag/"
    elif [ "$2" = "preprod" ]; then
        dirbase="/base/extranet/preprod/ext_aeag/"
    else
        dirbase="/base/extranet/dev/Vincent/ext_aeag/"
    fi
else
    dirbase="/base/extranet/dev/Vincent/ext_aeag/"
fi
dirlog=$dirbase"app/logs"
dircmd=$dirbase"app/console_process_rai"
if [ ! -d "$dirlog" ]; then
  mkdir $dirlog
fi
php $dircmd rai:check_sandre >> $dirlog/process_$jour.log

find $dirlog/process_* -mtime +14 -exec rm {} \;