#!/bin/bash
jour=$(date +"%Y%m%d")
dir="/base/extranet/preprod/ext_aeag/app/logs"
if [ ! -d "$dir" ]; then
  mkdir $dir
fi
/usr/local/bin/sqe/preprod/Validation_RAI_tmp/Validation_RAI_tmp/Validation_RAI_tmp_run.sh >> $dir/process_$jour.log