#!/bin/bash
jour=$(date +"%Y%m%d")
if [ "$1" = "-env" ]; then
    if [ "$2" = "prod" ]; then
        dirbase="/usr/local/bin"
        dirlog="/base/extranet/ext_aeag/app/logs"
    elif [ "$2" = "preprod" ]; then
        dirbase="/usr/local/bin/sqe/preprod"
        dirlog="/base/extranet/preprod/ext_aeag/app/logs"
    else
        dirbase="/usr/local/bin/sqe/dev"
        dirlog="/base/extranet/dev/Vincent/ext_aeag/app/logs"
    fi
else
    dirbase="/usr/local/bin/sqe/dev"
    dirlog="/base/extranet/dev/Vincent/ext_aeag/app/logs"
fi
if [ ! -d "$dirlog" ]; then
  mkdir $dirlog
fi
$dirbase/Validation_RAI_tmp/Validation_RAI_tmp/Validation_RAI_tmp_run.sh >> $dirlog/process_$jour.log