#!/bin/bash
jour=$(date +"%Y%m%d")
if [ "$1" = "-env" ]; then
    if [ "$2" = "prod" ]; then
        dirbase="/usr/local/bin"
    elif [ "$2" = "preprod" ]; then
        dirbase="/usr/local/bin/sqe/preprod"
    else
        dirbase="/usr/local/bin/sqe/dev"
    fi
else
    dirbase="/usr/local/bin/sqe/dev"
fi
dirlog=$dirbase"app/logs"
if [ ! -d "$dirlog" ]; then
  mkdir $dirlog
fi
$dirbase/Validation_RAI_tmp/Validation_RAI_tmp/Validation_RAI_tmp_run.sh >> $dirlog/process_$jour.log