security:
  
    encoders:
        FOS\UserBundle\Model\UserInterface: plaintext
           
  
    providers:
        fos_userbundle:
            id: fos_user.user_manager
  
    
    firewalls:
        dev:
            path:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Firewall pour les pages de connexion, inscription, et récupération de mot de passe
        login:
            path:   ^/(login$|register|resetting)  # Les adresses de ces pages sont login, register et resetting
            anonymous: true                           # On autorise bien évidemment les anonymes sur ces pages !

        # Firewall principal pour le reste de notre site
        main:
            path: ^/                      # ^/ = tout ce qui commence par / = tout notre site
            form_login:                      # On définit notre méthode d'authentification
                provider:    fos_userbundle  # On lit l'authentification au provider définit plus haut
                remember_me: true            # On active la possibilité du "Se souvenir de moi" (désactivé par défaut)
            remember_me:
                key:         %secret%        # On définit la clé pour le remember_me (%secret% est un parametre de parameters.ini)
            anonymous:       true            # On autorise les utilisateurs anonymes (non identifiés)
            logout:          true            # On autorise la déconnexion manuelle (désactivé par défaut)

    role_hierarchy:
        ROLE_ADMIN:  [ROLE_AEAG ]  
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH] # On garde ce rôle superadmin, il nous resservira par la suite

    access_control:
            # Liste des pages accessibles à tous les utilisateurs (ne pas toucher)
            - { path: ^/_wdt/, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/_profiler/, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/js/, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/css/, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/register$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/resseting$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            
            # PAGES ACCESSIBLES AUX ADMINISTRATEURS
            - { path: ^/admin, role: ROLE_ADMIN }
            - { path: ^/utilisateur, role: ROLE_ADMIN }
            
           # PAGES ACCESSIBLES AUX UTILISATEURS CONNECTES
            - { path: ^/change-password, role: [ROLE_AEAG] }
          
            # PAGES ACCESSIBLES À TOUS
            - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/*, role: IS_AUTHENTICATED_ANONYMOUSLY }