parameters:
#    aeag_gac.example.class: Aeag\FrdBundle\Example

services:
#    aeag_gac.example:
#        class: %aeag_frd.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
