<?php

namespace Aeag\EdlBundle\Entity;

use Doctrine\ORM\EntityRepository;
use JMS\SecurityExtraBundle\Annotation\Secure;
use Symfony\Component\HttpFoundation\Response;

/**
 * EtatMeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 * @Secure(roles="ROLE_SUPERVISEUR")
 * 
 */
class EtatMeRepository extends EntityRepository {

    public function getLastProposition($euCd, $cdEtat) {
        
        $qb = $this->_em->createQueryBuilder();

        try {
            $query = $qb->select('p') // string 'u' is converted to array internally
                    ->from('Aeag\EdlBundle\Entity\EtatMeProposed', 'p')
                    ->where('p.euCd = :euCd and p.cdEtat = :cdEtat and p.role = :role')
                    ->setParameter('euCd', $euCd)
                    ->setParameter('cdEtat', $cdEtat)
                    ->setParameter('role', 'expert')
                    ->orderBy('p.propositionDate', 'DESC')
                    ->setMaxResults(1)
                    ->getQuery();

            $r = $query->getResult();
            return reset($r);
        } catch (Exception $e) {
            return null;
        }
    }

    public function getEtatMe($code, $cdGroupe) {

        $query = "select e from Aeag\EdlBundle\Entity\MasseEau m";
        $query = $query . " , Aeag\EdlBundle\Entity\EtatType t";
        $query = $query . " , Aeag\EdlBundle\Entity\EtatMe e";
        $query = $query . " where m.euCd = e.euCd and e.cdEtat = t.cdEtat and m.typeMe = t.typeMe and m.euCd = '" . $code . "' and t.cdGroupe = '" . $cdGroupe . "'";
        //$query = $query . " and e.cdEtat != 'RW_ECO_VAL'";
        $query = $query . " order by t.ordre";
        // return new Response('query  : ' . $query);

        try {
            $r = $this->_em->createQuery($query)
                    ->getResult();
            return $r;
        } catch (Exception $e) {
            return null;
        }
    }
    
     public function getNbEtatMe($code, $cdGroupe) {

        $query = "select count(e) from Aeag\EdlBundle\Entity\MasseEau m";
        $query = $query . " , Aeag\EdlBundle\Entity\EtatType t";
        $query = $query . " , Aeag\EdlBundle\Entity\EtatMe e";
        $query = $query . " where m.euCd = e.euCd and e.cdEtat = t.cdEtat and m.typeMe = t.typeMe and m.euCd = '" . $code . "' and t.cdGroupe = '" . $cdGroupe . "'";
        //$query = $query . " and e.cdEtat != 'RW_ECO_VAL'";
        // return new Response('query  : ' . $query);

        try {
            $r = $this->_em->createQuery($query)
                    ->getSingleScalarResult();;
            return $r;
        } catch (Exception $e) {
            return null;
        }
    }
    
     public function getDerniereProposition($euCd) {
         
        
        $qb = $this->_em->createQueryBuilder();

        try {
            $query = $qb->select('p') // string 'u' is converted to array internally
                    ->from('Aeag\EdlBundle\Entity\EtatMeProposed', 'p')
                    ->where('p.euCd = :euCd ')
                    ->setParameter('euCd', $euCd)
                    ->orderBy('p.propositionDate', 'DESC')
                    ->setMaxResults(1)
                    ->getQuery();

            $r = $query->getResult();
            return reset($r);
        } catch (Exception $e) {
            return null;
        }
    }

}