<?php

namespace Aeag\EdlBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\HttpFoundation\Response;

/**
 * ImpactGroupeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 * 
 * 
 */
class ImpactGroupeRepository extends EntityRepository {

    public function getImpactGroupe() {


        $query = "select e from Aeag\EdlBundle\Entity\ImpactGroupe e";
        $query = $query . " order by e.ordre";
        // return new Response('query  : ' . $query);

        try {
            $r = $this->_em->createQuery($query)
                    ->getResult();
            return $r;
        } catch (Exception $e) {
            return null;
        }
    }

}