<?php

namespace Aeag\EdlBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ImpactMeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImpactMeRepository extends EntityRepository {

    public function getLastProposition($euCd, $cdImpact) {
        $qb = $this->_em->createQueryBuilder();

        try {
            $query = $qb->select('p') // string 'u' is converted to array internally
                    ->from('Aeag\EdlBundle\Entity\ImpactMeProposed', 'p')
                    ->where('p.euCd = :euCd and p.cdImpact = :cdImpact  and p.role = :role')
                    ->setParameter('euCd', $euCd)
                    ->setParameter('cdImpact', $cdImpact)
                    ->setParameter('role', 'expert')
                    ->orderBy('p.propositionDate', 'DESC')
                    ->setMaxResults(1)
                    ->getQuery();

            $r = $query->getResult();
            return reset($r);
        } catch (Exception $e) {
            return null;
        }
    }

    public function getImpactMe($code, $cdGroupe) {

        $query = "select e from Aeag\EdlBundle\Entity\MasseEau m";
        $query = $query . " , Aeag\EdlBundle\Entity\ImpactType t";
        $query = $query . " , Aeag\EdlBundle\Entity\IMpactMe e";
        $query = $query . " where m.euCd = e.euCd and e.cdImpact = t.cdImpact and m.typeMe = t.typeMe and m.euCd = '" . $code . "' and t.cdGroupe = '" . $cdGroupe . "'";
        $query = $query . " order by t.ordre";
        // return new Response('query  : ' . $query);

        try {
            $r = $this->_em->createQuery($query)
                    ->getResult();
            return $r;
        } catch (Exception $e) {
            return null;
        }
    }

    public function getNbImpactMe($code, $cdGroupe) {

        $query = "select count(e) from Aeag\EdlBundle\Entity\MasseEau m";
        $query = $query . " , Aeag\EdlBundle\Entity\ImpactType t";
        $query = $query . " , Aeag\EdlBundle\Entity\IMpactMe e";
        $query = $query . " where m.euCd = e.euCd and e.cdImpact = t.cdImpact and m.typeMe = t.typeMe and m.euCd = '" . $code . "' and t.cdGroupe = '" . $cdGroupe . "'";
        //$query = $query . " and e.cdImpact != 'RW_ECO_VAL'";
        // return new Response('query  : ' . $query);

        try {
            $r = $this->_em->createQuery($query)
                    ->getSingleScalarResult();
            ;
            return $r;
        } catch (Exception $e) {
            return null;
        }
    }

     public function getDerniereProposition($euCd) {
        $qb = $this->_em->createQueryBuilder();

        try {
            $query = $qb->select('p') // string 'u' is converted to array internally
                    ->from('Aeag\EdlBundle\Entity\ImpactMeProposed', 'p')
                    ->where('p.euCd = :euCd')
                    ->setParameter('euCd', $euCd)
                    ->orderBy('p.propositionDate', 'DESC')
                    ->setMaxResults(1)
                    ->getQuery();

            $r = $query->getResult();
            return reset($r);
        } catch (Exception $e) {
            return null;
        }
    }
}