<?php

namespace Aeag\EdlBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\HttpFoundation\Response;

/**
 * AvisHistoriqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 * 
 */
class AvisHistoriqueRepository extends EntityRepository {

    public function getAvisHistorique() {

        $query = "select e ";
        $query = $query . " from Aeag\EdlBundle\Entity\AvisHistorique e";
        $query = $query . " order by e.code, e.epr";
        $qb = $this->_em->createQuery($query);
        //print_r($query);
        return $qb->getResult();
    }

    public function getAvisHistoriqueByCodeEpr($code, $epr) {

        $query = "select e ";
        $query = $query . " from Aeag\EdlBundle\Entity\AvisHistorique e";
        $query = $query . " where e.euCd = :code and e.epr = :epr ";
        $qb = $this->_em->createQuery($query);
        $qb->setParameter('code', $code);
        $qb->setParameter('epr', $epr);
        //print_r($query);
        return $qb->getOneOrNullResult();
    }

}
