<?php

namespace Aeag\EdlBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\HttpFoundation\Response;

/**
 * EtatGroupeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 * 
 * 
 */
class EtatGroupeRepository extends EntityRepository {

    public function getEtatGroupe() {


        $query = "select e from Aeag\EdlBundle\Entity\EtatGroupe e";
        $query = $query . " order by e.ordre";
        // return new Response('query  : ' . $query);

        try {
            $r = $this->_em->createQuery($query)
                    ->getResult();
            return $r;
        } catch (Exception $e) {
            return null;
        }
    }

}