<?php

namespace Aeag\EdlBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\HttpFoundation\Response;

/**
 * ExportAvisPressionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 * 
 */
class ExportAvisPressionRepository extends EntityRepository {

   /**
     * @return array
     */
    public function getExportAvisPressions() {
        $query = "select a";
        $query = $query . " from Aeag\EdlBundle\Entity\ExportAvisPression a";
         $query = $query . ' order by a.gOrdre, a.typPordre';
        $qb = $this->_em->createQuery($query);
        //print_r($query);
        return $qb->getResult();
    }
    
    /**
     * @return array
     */
    public function getExportAvisPressionByWhere($where) {
        $query = "select a";
        $query = $query . " from Aeag\EdlBundle\Entity\ExportAvisPression a ";
        if ($where){
        $query = $query . ' where ' . $where;
        }
        $query = $query . ' order by a.gOrdre, a.typPordre';
        $qb = $this->_em->createQuery($query);
        //print_r($query);
        return $qb->getResult();
    }

   
 
}
