<?php

namespace Aeag\EdlBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\HttpFoundation\Response;

/**
 * EtatMeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 * 
 */
class MasseEauRepository extends EntityRepository {

    public function getMasseEau($euCd, $groupe) {


        $query = "select m from Aeag\EdlBundle\Entity\MasseEau m";
        $query = $query . " , Aeag\EdlBundle\Entity\EtatType t";
        $query = $query . " where m.typeMe = t.typeMe and m.euCd = :euCd and t.cdGroupe = :groupe";
        $query = $query . " order by t.ordre";

        $qb = $this->_em->createQuery($query);
        $qb->setParameter('euCd', $euCd);
        $qb->setParameter('groupe', $groupe);
        //print_r($query);
        return $qb->getResult();
    }

}
