<?php

namespace Aeag\EdlBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RisqueMeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RisqueMeRepository extends EntityRepository {

    public function getLastProposition($euCd, $cdRisque) {
        $qb = $this->_em->createQueryBuilder();

        try {
            $query = $qb->select('p') // string 'u' is converted to array internally
                    ->from('Aeag\EdlBundle\Entity\RisqueMeProposed', 'p')
                    ->where('p.euCd = :euCd and p.cdRisque = :cdRisque and p.role = :role')
                    ->setParameter('euCd', $euCd)
                    ->setParameter('cdRisque', $cdRisque)
                    ->setParameter('role', 'expert')
                    ->orderBy('p.propositionDate', 'DESC')
                    ->setMaxResults(1)
                    ->getQuery();

            $r = $query->getResult();
            return reset($r);
        } catch (Exception $e) {
            return null;
        }
    }
    
      public function getRisqueMe($code, $cdGroupe) {

        $query = "select e from Aeag\EdlBundle\Entity\MasseEau m";
        $query = $query . " , Aeag\EdlBundle\Entity\RisqueType t";
        $query = $query . " , Aeag\EdlBundle\Entity\RisqueMe e";
        $query = $query . " where m.euCd = e.euCd and e.cdRisque = t.cdRisque and m.typeMe = t.typeMe and m.euCd = '" . $code . "' and t.cdGroupe = '" . $cdGroupe . "'";
        $query = $query . " order by t.ordre";
        // return new Response('query  : ' . $query);

        try {
            $r = $this->_em->createQuery($query)
                    ->getResult();
            return $r;
        } catch (Exception $e) {
            return null;
        }
    }

    public function getNbRisqueMe($code, $cdGroupe) {

        $query = "select count(e) from Aeag\EdlBundle\Entity\MasseEau m";
        $query = $query . " , Aeag\EdlBundle\Entity\RisqueType t";
        $query = $query . " , Aeag\EdlBundle\Entity\RisqueMe e";
        $query = $query . " where m.euCd = e.euCd and e.cdRisque = t.cdRisque and m.typeMe = t.typeMe and m.euCd = '" . $code . "' and t.cdGroupe = '" . $cdGroupe . "'";
        //$query = $query . " and e.cdRisque != 'RW_ECO_VAL'";
        // return new Response('query  : ' . $query);

        try {
            $r = $this->_em->createQuery($query)
                    ->getSingleScalarResult();
            ;
            return $r;
        } catch (Exception $e) {
            return null;
        }
    }
    
      public function getDerniereProposition($euCd) {
        $qb = $this->_em->createQueryBuilder();

        try {
            $query = $qb->select('p') // string 'u' is converted to array internally
                    ->from('Aeag\EdlBundle\Entity\RisqueMeProposed', 'p')
                    ->where('p.euCd = :euCd ')
                    ->setParameter('euCd', $euCd)
                    ->orderBy('p.propositionDate', 'DESC')
                    ->setMaxResults(1)
                    ->getQuery();

            $r = $query->getResult();
            return reset($r);
        } catch (Exception $e) {
            return null;
        }
    }


}