parameters:
#    aeag_die.example.class: Aeag\DieBundle\Example

services:
#    aeag_die.example:
#        class: %aeag_die.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
